name: Build & Deploy (no external actions)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      SHA: ${{ github.sha }}
      REF_NAME: ${{ github.ref_name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BASE_PATH: /${{ github.event.repository.name }}/

    steps:
      - name: Checkout (manual)
        run: |
          set -e
          git init .
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"
          git fetch --no-tags --depth=1 origin "${SHA}"
          git checkout --progress --force "${SHA}"
          git log -1 --oneline

      - name: Setup Node
        run: |
          set -e
          if ! command -v node >/dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          v=$(node -v | sed 's/v\([0-9]\+\).*/\1/')
          if [ "$v" -lt 18 ]; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          node -v
          npm -v

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: (Optional) Sync Google Drive
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          if [ -n "$GOOGLE_API_KEY" ]; then
            set +e
            npm run sync:drive
            code=$?
            if [ $code -ne 0 ]; then
              echo "::warning::Drive sync failed (code=$code). Continuing deployment with existing JSON."
            fi
            set -e
          else
            echo "GOOGLE_API_KEY not set; skipping Drive sync."
          fi

      - name: Build site
        run: |
          ELEVENTY_BASE="$BASE_PATH" npm run build
          npx pagefind --site _site

      - name: Deploy to gh-pages
        run: |
          set -e
          cd _site
          touch .nojekyll
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy ${SHA} ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
          git branch -M gh-pages
          git push -f "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" gh-pages
